#!/usr/bin/env python3
#
# Redundant slot image builder.
#
# Wraps an HSS boot image blob (from tools/hss-payload-generator) in the
# N-slot x M-copy redundant layout described in
# docs/DESIGN-redundant-slot-boot.md, and/or emits the matching
# hss_slot_layout.h for the firmware.
#
# This is deliberately a separate tool from hss-payload-generator: it writes
# the *slot* wrapper, never the blob format, so the "one writer of the blob
# format" rule is preserved.  If the map later needs to be authored as
# slot-map.yaml, fold --slot-map parsing in here first.
#
import argparse
import binascii
import os
import struct
import sys

HSS_SLOT_MAGIC = 0x534C4F54  # 'SLOT'
HSS_SLOT_VERSION = 3
HSS_SLOT_HDR_SIZE = 48

# production: MT25QU02G, 256 MiB
PROD = dict(base=0x0010000, capacity=0x2200000, slots=2, copies=3, part_size=0x10000000)
# QEMU: emulated 32 MiB n25q256a
QEMU = dict(base=0x0010000, capacity=0x500000, slots=2, copies=3, part_size=0x2000000)

HDR_FMT = "<10IQ"


def crc32(data):
    return binascii.crc32(data) & 0xFFFFFFFF


def stride(layout):
    return layout["slots"] * layout["capacity"]


def region(layout, slot, copy):
    return layout["base"] + copy * stride(layout) + slot * layout["capacity"]


def layout_end(layout):
    return layout["base"] + layout["copies"] * stride(layout)


def build_header(layout, slot, copy, blob, owner_hart, content_version,
                 corrupt_header=False):
    off = region(layout, slot, copy)
    fields = [
        HSS_SLOT_MAGIC,
        HSS_SLOT_VERSION,
        slot,
        copy,
        len(blob),
        crc32(blob),
        0,  # headerCrc, patched below
        owner_hart,
        content_version,
        0,  # reserved0
        off,
    ]
    hdr = struct.pack(HDR_FMT, *fields)
    assert len(hdr) == HSS_SLOT_HDR_SIZE, len(hdr)
    crc = crc32(hdr)
    hdr = struct.pack(HDR_FMT, *fields[:6], crc, *fields[7:])
    if corrupt_header:
        hdr = hdr[:6] + struct.pack("<I", crc ^ 0xFFFFFFFF) + hdr[10:]
    return hdr


def self_test(layout, blobs):
    n, m, c, base = (layout["slots"], layout["copies"], layout["capacity"],
                     layout["base"])
    s, gap = stride(layout), (layout["slots"] - 1) * layout["capacity"]
    end = layout_end(layout)

    assert base % 0x10000 == 0, "base not 64 KiB aligned"
    assert c % 0x10000 == 0, "capacity not 64 KiB aligned"
    assert s == n * c, "stride != N*c"
    assert gap == (n - 1) * c, "gap != (N-1)*c"
    assert end == base + m * s, "layout end != base + M*stride"

    seen = set()
    for k in range(m):
        band = (base + k * s, base + (k + 1) * s)
        for slot in range(n):
            off = region(layout, slot, k)
            assert band[0] <= off < band[1], "region outside its band"
            assert off + c <= band[1], "region overruns its band"
            assert off % 0x10000 == 0, "region not 64 KiB aligned"
            assert off not in seen, "region overlap"
            seen.add(off)

    for slot, blob in blobs.items():
        assert c >= HSS_SLOT_HDR_SIZE + len(blob), \
            "slot %d blob does not fit capacity" % slot
        for k in range(m):
            hdr = build_header(layout, slot, k, blob, 1, 0)
            assert hdr[:4] == struct.pack("<I", HSS_SLOT_MAGIC)

    if layout.get("part_size"):
        assert end <= layout["part_size"], \
            "layout end 0x%x exceeds part size 0x%x" % (end, layout["part_size"])


def emit_header(layout, path):
    with open(path, "w") as f:
        f.write("/* generated by tools/slot-image/make-slot-image.py "
                "- do not edit */\n")
        f.write("#define HSS_SLOT_BASE     0x%08xu\n" % layout["base"])
        f.write("#define HSS_SLOT_CAPACITY 0x%08xu\n" % layout["capacity"])
        f.write("#define HSS_SLOT_COUNT    %uu\n" % layout["slots"])
        f.write("#define HSS_SLOT_COPIES   %uu\n" % layout["copies"])
    hdr_dir = os.path.dirname(os.path.abspath(path))
    walker = os.path.join(hdr_dir, "hss_boot_slotimage.c")
    if os.path.exists(walker):
        # The build has no dependency edge on this header (it is picked up by
        # __has_include), so a re-emit would otherwise reuse a stale object.
        os.utime(walker)
    print("wrote %s" % path)


def emit_image(layout, blobs, path, owner_hart, content_version, corrupt,
               corrupt_header):
    end = layout_end(layout)
    size = layout.get("part_size") or end
    img = bytearray(b"\xff" * size)
    for slot, blob in blobs.items():
        for copy in range(layout["copies"]):
            off = region(layout, slot, copy)
            bad = (slot, copy) in corrupt
            bad_hdr = (slot, copy) in corrupt_header
            hdr = build_header(layout, slot, copy, blob, owner_hart,
                               content_version, corrupt_header=bad_hdr)
            data = bytearray(blob)
            if bad:
                for i in corrupt[(slot, copy)]:
                    data[i] ^= 0xFF
            img[off:off + len(hdr)] = hdr
            img[off + HSS_SLOT_HDR_SIZE:off + HSS_SLOT_HDR_SIZE + len(data)] = data
    with open(path, "wb") as f:
        f.write(img)
    print("wrote %s (%d bytes, layout end 0x%x)" % (path, len(img), end))


def emit_slot(layout, blobs, slot, outdir, owner_hart, content_version):
    import os
    os.makedirs(outdir, exist_ok=True)
    blob = blobs[slot]
    lines = []
    for copy in range(layout["copies"]):
        off = region(layout, slot, copy)
        hdr = build_header(layout, slot, copy, blob, owner_hart, content_version)
        path = os.path.join(outdir, "slot%c.copy%d.bin" % (ord('A') + slot, copy))
        with open(path, "wb") as f:
            f.write(hdr + blob)
        lines.append("slot %d copy %d  offset 0x%08x  %s" % (slot, copy, off, path))
    offs = os.path.join(outdir, "offsets.txt")
    with open(offs, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s" % outdir)


def parse_corrupt(spec):
    out = {}
    for item in spec or []:
        loc, _, count = item.partition(":")
        slot, _, copy = loc.partition(",")
        out.setdefault((int(slot), int(copy)), list(range(int(count or 1))))
    return out


def main(argv):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--qemu", action="store_true",
                   help="use the scaled 32 MiB QEMU map")
    p.add_argument("--base", type=lambda x: int(x, 0))
    p.add_argument("--capacity", type=lambda x: int(x, 0))
    p.add_argument("--slots", type=int)
    p.add_argument("--copies", type=int)
    p.add_argument("--part-size", type=lambda x: int(x, 0))
    p.add_argument("--slot", action="append", default=[], metavar="S:FILE",
                   help="blob for slot S (S is 0-based); repeatable")
    p.add_argument("--emit-header", metavar="PATH")
    p.add_argument("--image", metavar="PATH")
    p.add_argument("--emit-slot", nargs=2, metavar=("S", "DIR"))
    p.add_argument("--owner-hart", type=int, default=1)
    p.add_argument("--content-version", type=lambda x: int(x, 0), default=0)
    p.add_argument("--corrupt", action="append", metavar="S,K[:N]",
                   help="flip N bytes of slot S copy K payload")
    p.add_argument("--corrupt-header", action="append", metavar="S,K")
    p.add_argument("--self-test", action="store_true")
    args = p.parse_args(argv)

    layout = dict(QEMU if args.qemu else PROD)
    for key in ("base", "capacity", "slots", "copies", "part_size"):
        if getattr(args, key) is not None:
            layout[key] = getattr(args, key)

    blobs = {}
    for item in args.slot:
        s, _, path = item.partition(":")
        with open(path, "rb") as f:
            blobs[int(s)] = f.read()

    corrupt = parse_corrupt(args.corrupt)
    corrupt_hdr = set()
    for item in args.corrupt_header or []:
        s, _, k = item.partition(",")
        corrupt_hdr.add((int(s), int(k)))

    if args.self_test:
        self_test(layout, blobs)
        print("self-test: PASS")

    if args.emit_header:
        emit_header(layout, args.emit_header)
    if args.emit_slot:
        slot = int(args.emit_slot[0])
        emit_slot(layout, blobs, slot, args.emit_slot[1], args.owner_hart,
                  args.content_version)
    if args.image:
        emit_image(layout, blobs, args.image, args.owner_hart,
                   args.content_version, corrupt, corrupt_hdr)

    if not (args.self_test or args.emit_header or args.image or args.emit_slot):
        p.error("nothing to do: use --self-test/--emit-header/--image/--emit-slot")

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
